### ISSUE TITLE
Doesn't work with my kubeconfig file. 

### ISSUE THREAD

**Issue by anjuls** [vchinnipilli/kubestrike#6]
```
apiVersion: v1
kind: Config
clusters:
- name: "xxxx-cluster7"
  cluster:
    server: "https://xxxxx.com/k8s/clusters/c-hkpbf"

users:
- name: "xxxx-cluster7"
  user:
    token: "kubeconfig-user-swrnv:*******************************************************"


contexts:
- name: "xxxx-cluster7"
  context:
    user: "xxxx-cluster7"
    cluster: "xxxx-cluster7"

current-context: "xxxx-cluster7"
```

After selecting option 2 (configfile) -> default, it gives me HTTPS URL to select and then it fails. saying input is not valid.
